<<<<<<< HEAD
=======
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
>>>>>>> 12c406d800755276ebafeafea08eef31879660c5
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
<<<<<<< HEAD
  schema: "prisma/schema",
=======
  schema: "prisma/schema.prisma",
>>>>>>> 12c406d800755276ebafeafea08eef31879660c5
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
<<<<<<< HEAD
    url: process.env["DATABASE_URL"] as string,
=======
    url: process.env["DATABASE_URL"],
>>>>>>> 12c406d800755276ebafeafea08eef31879660c5
  },
});
